spring:
  application:
    name: dnscache

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

dns:
  ttl: 300
  fallback-servers:
    - 8.8.8.8
    - 1.1.1.1
    - 9.9.9.9

info:
  app:
    name: Smart DNS Cache
    description: In-house reactive DNS caching system
    version: 1.0.0