version: "3.8"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  dnscache:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_REDIS_HOST: redis
    ports: ["8080:8080"]
    depends_on: [redis]
