name: Build & Push Backend Docker Image

on:
  push:
    paths:
      - 'dnscache/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend with Maven
        working-directory: dnscache
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t zzeng45/dnscache-backend:latest ./dnscache

      - name: Push Docker image
        run: docker push zzeng45/dnscache-backend:latest
